services:
  - type: web
    name: backend-notion-gpt
    env: python
    plan: free
    buildCommand: ""
    startCommand: gunicorn backend_notion_viagens:app
    envVars:
      - key: NOTION_API_KEY
        value: "substitua_por_seu_token"
      - key: NOTION_DATABASE_ID
        value: "substitua_pelo_id_da_database"
      - key: TWILIO_ACCOUNT_SID
        value: "substitua_pelo_seu_sid"
      - key: TWILIO_AUTH_TOKEN
        value: "substitua_pelo_seu_auth_token"
      - key: TWILIO_DESTINO
        value: "whatsapp:+5581XXXXXXXXX"
